name: Build and push to github package repository

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to docker
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: mishrasunny174
        password: ${{ secrets.GH_PAT }}
    
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/pwn-docker:latest