name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push latest docker image
      uses: docker/build-push-action@v1.1.0
      with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.DOCKER_PASSWORD }}
          # repository to push image to
          repository: mishrasunny174/pwn-docker
          # tag
          tags: latest
          # dockerfile
          dockerfile: Dockerfile
      
    - name: Build and push glibc-2.23 docker image
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PASSWORD }}
        # repository to push image to
        repository: mishrasunny174/pwn-docker
        # tag
        tags: glibc-2.23
        # dockerfile
        dockerfile: Dockerfile.glibc2.23

    - name: Build and push glibc-2.27 docker image
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PASSWORD }}
        # repository to push image to
        repository: mishrasunny174/pwn-docker
        # tag
        tags: glibc-2.27
        # dockerfile
        dockerfile: Dockerfile.glibc2.27

    - name: Build and push glibc-2.30 docker image
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PASSWORD }}
        # repository to push image to
        repository: mishrasunny174/pwn-docker
        # tag
        tags: glibc-2.30
        # dockerfile
        dockerfile: Dockerfile.glibc2.30
    
    - name: Build and push glibc-2.31 docker image
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PASSWORD }}
        # repository to push image to
        repository: mishrasunny174/pwn-docker
        # tag
        tags: glibc-2.31
        # dockerfile
        dockerfile: Dockerfile.glibc2.31